instagram:
  id: '10ca4b8fa19c46b087ea2ed63dbdeadf'
  secret: '5a358f38e6594f74bf442a0d25b15937'

database:
  username: 'lwygkihhlhqlqa'
  password: '6yJq5CdBbBzU-Qy_aa9EHcYb4w'
  db: 'dburpdce044j2i'
  host: 'ec2-54-163-255-191.compute-1.amazonaws.com'